---
title: "beta_diversity"
output: html_document
---

```{r}
# Load in packages
library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)
library(microbiome)
library(indicspecies)
library(writexl)
library(ANCOMBC)
```

```{r}
# Load in data
metadata = read.delim('../project_analyses/depression_metadata_full.txt', row.names = 1)

metadata$antidepressant_on_off = as.factor(metadata$antidepressant_on_off)
metadata <- metadata %>%
  select(Assay.Type, antidepressant_on_off, antidepressant_count, bdi_group, bdi_ii,
         hiv_status_clean, hcv) %>%
  mutate(antidepressant_on_off = recode(antidepressant_on_off,
                                        `0` = "Off", `1` = "On")) %>%
  filter(!is.na(antidepressant_on_off) & hcv == "NO" &
           hiv_status_clean == "HIV+" & bdi_group != "minimal" &
           Assay.Type == "AMPLICON")

taxonomy = read.delim('../project_analyses/taxonomy.tsv', row.names = 1)
counts = read.delim('../project_analyses/feature-table.txt', skip=1, row.names=1)
phylotree = read_tree('../project_analyses/tree.nwk')
```

```{r}
# Make phyloseq object
set.seed(123)
taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon, 
           into = c('Domain','Phylum','Class','Order',
                    'Family','Genus','Species'),
           sep=';', fill='right') %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()

otu_table <- otu_table(counts_formatted, taxa_are_rows = T)

sample_data <- sample_data(metadata)

tax_table <- tax_table(taxonomy_formatted)

ps <- phyloseq(otu_table, sample_data, tax_table, phylotree)
ps = readRDS("../project_analyses/phyloseq_taxonomy.rds")
```

```{r}
# Rarify data
set.seed(123)
psrare = ps %>%
  rarefy_even_depth(sample.size = 20000, rngseed = 123)
```

```{r}
# Calculate Bray-Curtis distances
set.seed(123)
ps_wunifrac = phyloseq::distance(psrare, method = "wunifrac")
```

```{r}
# Normalize and plot
set.seed(123)
mds = metaMDS(ps_wunifrac)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare), by='row.names', sort=F)

mds_data = mds_data %>%
  filter(Row.names != "ERR4254382")

# Plot it
p_wunifrac = mds_data %>%
  ggplot(aes(MDS1,MDS2,color = antidepressant_on_off)) +
  geom_point(size = 0.5, alpha = 0.5) +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  scale_color_manual(values = c("Off" = "#6633FF","On"  = "#00FFCC" ))
p_wunifrac

ggsave("beta_diversity_plots/bdiv_wunifrac_plot.png", plot = p_wunifrac)
```

```{r}
# PERMANOVA
metadata2 = sample_data(psrare) %>% data.frame()

stats_univar = adonis2(ps_wunifrac ~ antidepressant_on_off, data = metadata2)

stats = bind_rows('Univariate' = stats_univar %>% as.data.frame() %>% 
                    rownames_to_column('Variable'),
                  .id = 'Model')

stats = stats %>% rename(Pval = `Pr(>F)`) %>%
  filter(!is.na(Pval))

stats
```

```{r}
set.seed(123)
ps_bray = phyloseq::distance(psrare, method = "bray")

mds = metaMDS(ps_bray)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare), by='row.names', sort=F)

# Plot it
p_bray = mds_data %>%
  ggplot(aes(MDS1,MDS2,color = antidepressant_on_off)) +
  geom_point(size = 0.5, alpha = 0.5) +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  scale_color_manual(values = c("Off" = "#6633FF","On"  = "#00FFCC" ))
p_bray

ggsave("beta_diversity_plots/bdiv_bray_plot.png", plot = p_bray)

metadata2 = sample_data(psrare) %>% data.frame()

stats_univar = adonis2(ps_bray ~ antidepressant_on_off, data = metadata2)

stats = bind_rows('Univariate' = stats_univar %>% as.data.frame() %>% 
                    rownames_to_column('Variable'),
                  .id = 'Model')

stats = stats %>% rename(Pval = `Pr(>F)`) %>%
  filter(!is.na(Pval))

stats
```

```{r}
set.seed(123)
ps_jaccard = phyloseq::distance(psrare, method = "jaccard")

mds = metaMDS(ps_jaccard)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare), by='row.names', sort=F)

# Plot it
p_jaccard = mds_data %>%
  ggplot(aes(MDS1,MDS2,color = antidepressant_on_off)) +
  geom_point(size = 0.5, alpha = 0.5) +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  scale_color_manual(values = c("Off" = "#6633FF","On"  = "#00FFCC" ))
p_jaccard

ggsave("beta_diversity_plots/bdiv_jaccard_plot.png", plot = p_jaccard)

metadata2 = sample_data(psrare) %>% data.frame()

stats_univar = adonis2(ps_jaccard ~ antidepressant_on_off, data = metadata2)

stats = bind_rows('Univariate' = stats_univar %>% as.data.frame() %>% 
                    rownames_to_column('Variable'),
                  .id = 'Model')

stats = stats %>% rename(Pval = `Pr(>F)`) %>%
  filter(!is.na(Pval))

stats
```

```{r}
set.seed(123)
ps_unifrac = phyloseq::distance(psrare, method = "unifrac")

mds = metaMDS(ps_unifrac)

# Extract data
mds_data = mds$points %>% as.data.frame %>%
  merge(sample_data(psrare), by='row.names', sort=F)

# Plot it
p_unifrac = mds_data %>%
  ggplot(aes(MDS1,MDS2,color = antidepressant_on_off)) +
  geom_point(size = 0.5, alpha = 0.5) +
  stat_ellipse() +
  theme_classic(base_size = 18) +
  scale_color_manual(values = c("Off" = "#6633FF","On"  = "#00FFCC" ))
p_unifrac

ggsave("beta_diversity_plots/bdiv_unifrac_plot.png", plot = p_unifrac)

metadata2 = sample_data(psrare) %>% data.frame()

stats_univar = adonis2(ps_unifrac ~ antidepressant_on_off, data = metadata2)

stats = bind_rows('Univariate' = stats_univar %>% as.data.frame() %>% 
                    rownames_to_column('Variable'),
                  .id = 'Model')

stats = stats %>% rename(Pval = `Pr(>F)`) %>%
  filter(!is.na(Pval))

stats
```
